In [1]:
import numpy as np

In [2]:
def FindEVs( matrix ) :

    print( f"matrix : \n{ matrix }\n" )
    eigvals = np.linalg.eig( matrix )

    print(f" EigenValues : \n{ eigvals[0] } \n")
    print(f" EigenVecs : \n{ eigvals[1] } ")

In [3]:
matrix = np.array( [
    [0 , 5 ,-10] ,
    [0 ,22 , 16] ,
    [0 ,-9 ,-2 ]

] )

immatrix = np.array( [
    [3 , -2] ,
    [4 ,  1]
] )

In [4]:
eigvals = np.linalg.eig( matrix )

In [5]:
FindEVs( matrix )

matrix : 
[[  0   5 -10]
 [  0  22  16]
 [  0  -9  -2]]

 EigenValues : 
[ 0. 10. 10.] 

 EigenVecs : 
[[ 1.          0.70710678 -0.70710678]
 [ 0.          0.56568542 -0.56568542]
 [ 0.         -0.42426407  0.42426407]] 


In [6]:
FindEVs( immatrix )

matrix : 
[[ 3 -2]
 [ 4  1]]

 EigenValues : 
[2.+2.64575131j 2.-2.64575131j] 

 EigenVecs : 
[[0.20412415+0.54006172j 0.20412415-0.54006172j]
 [0.81649658+0.j         0.81649658-0.j        ]] 


In [7]:
sksm = np.array([
    [  0, -2,  45] ,
    [  2,  0,  4 ] ,
    [-45, -4 , 0 ]
])

In [8]:
FindEVs( sksm )

matrix : 
[[  0  -2  45]
 [  2   0   4]
 [-45  -4   0]]

 EigenValues : 
[-3.33066907e-16+45.22167622j -3.33066907e-16-45.22167622j
  6.26033980e-16 +0.j        ] 

 EigenVecs : 
[[ 0.0027689 -0.70432972j  0.0027689 +0.70432972j -0.08845316+0.j        ]
 [-0.03115009-0.06260709j -0.03115009+0.06260709j  0.99509801+0.j        ]
 [ 0.7064149 +0.j          0.7064149 -0.j          0.04422658+0.j        ]] 


In [9]:
sym = np.transpose( -sksm )
FindEVs( sym )

matrix : 
[[  0  -2  45]
 [  2   0   4]
 [-45  -4   0]]

 EigenValues : 
[-3.33066907e-16+45.22167622j -3.33066907e-16-45.22167622j
  6.26033980e-16 +0.j        ] 

 EigenVecs : 
[[ 0.0027689 -0.70432972j  0.0027689 +0.70432972j -0.08845316+0.j        ]
 [-0.03115009-0.06260709j -0.03115009+0.06260709j  0.99509801+0.j        ]
 [ 0.7064149 +0.j          0.7064149 -0.j          0.04422658+0.j        ]] 
